### ISSUE TITLE
{REQ} Can Update For Faster?

### ISSUE THREAD

**Issue by AhrimanSefid** [DavidMGilbert/btc-hack#1]
Hi And thank you.
{REQ} Can Update For Faster?
My Pc Info :
48 cores - 384 GB RAM - 4T SSDN Disk

**Comment by DavidMGilbert** [comment]
You can enable multi-threading and speed up address generation, however the current API I have access to only allows 300 queries per minute from a single IP address. Until I can build a local API that can piggy back the full node and extract the address balances with some degree of speed and accuracy, we will be limited to the free online API.

**Comment by fishinstud** [comment]
looking forward to seeing speed improvments

**Comment by AhrimanSefid** [comment]
https://sochain.com/api#realtime-balance-updates
api good me test work.

https://www.homebitcoin.com/easybalance/
