### ISSUE TITLE
Py script error


When i execute btc-hack.py
I get the error
Line 20 in module
Pool. Close=()
Name "pool" is not defined

### ISSUE THREAD

**Issue by Parag0014** [DavidMGilbert/btc-hack#10]

**Comment by PurpIeHaze** [comment]
Use `pip install multiprocessing` if you are still experiencing this issue. 

@DavidMGilbert you can close most of these issues I have solved

**Comment by Fastnicky13** [comment]
Pip install multiprocessing and pip install - r requirements.txt still gets pool error

**Comment by sathish23M** [comment]
Error opening ""Traceback (most recent call last):
  File "/data/data/com.termux/files/home/%%/btc-hack.py", line 120, in <module>
    pool.close()
NameError: name 'pool' is not defined. Did you mean: 'bool'?""
