### ISSUE TITLE
PLZ HELP Py Install Code Error 
Pool not defined 

### ISSUE THREAD

**Issue by lamia787** [DavidMGilbert/btc-hack#11]
![Screenshot_20210501-112759_Termux.jpg](https://user-images.githubusercontent.com/69842837/116766924-6acfe280-aa70-11eb-886a-89544e644365.jpg)

![Screenshot_20210501-112741_Termux.jpg](https://user-images.githubusercontent.com/69842837/116766938-76bba480-aa70-11eb-9a99-ceabb206e001.jpg)

**Comment by PurpIeHaze** [comment]
We can see the problem in the traceback . `pool = ThreadPool(processes = multiprocessing.cpu_count()*2)` and `line 120, in <module> pool.close() NameError: name 'pool is not defined'`

Essentially you didn't install the requirements. In the provided requirements.txt folder, the project creator forgot to include multiprocessing. So type `pip install multiprocessing` and you should be good to go.
Hope this helps

**Comment by Fastnicky13** [comment]
Nope. I've downloaded requirements and multiprocessing and still getting the pool error

**Comment by sathish23M** [comment]
Me also same error pool
