### ISSUE TITLE
need help with cloning and starting scrypt

### ISSUE THREAD

**Issue by pujaguja** [DavidMGilbert/btc-hack#13]
can anyone tell me what operating system do we need for this comands?for instalation and runing scrypt

**Comment by PurpIeHaze** [comment]
You can use this script on windows or linux. 
First go to your terminal and copy and paste this command: git clone https://github.com/DavidMGilbert/btc-hack.git btc-hack

If you get an error like "cannot find git" or "cannot find file specified" you have to type pip install git (linux: apt install git)

Second type this command "py -m pip install -r requirements.txt" so you can install the specified requirements for this project. 
lastly just double click btc-hack.py or you can go to your terminal and type "py (or python) btc-hack.py" and it should work

**Comment by PurpIeHaze** [comment]
Make sure to type "cd btc-hack" after cloning the repository

**Comment by sathish23M** [comment]
Error showing 'Traceback (most recent call last):
  File "/data/data/com.termux/files/home/btc-hack/btc-hack.py", line 120, in <module>
    pool.close()
NameError: name 'pool' is not defined. Did you mean: 'bool'?
