### ISSUE TITLE
pool.close() NameError: name 'pool' is not defined

### ISSUE THREAD

**Issue by amith598** [DavidMGilbert/btc-hack#14]

**Comment by ikrahul** [comment]
You're trying to run the script on Termux I guess.
To make it work on termux you have to install ubuntu 18 on termux and then git clone the repo in it. It'll work seemlessly.

**Comment by sathish23M** [comment]
Error ''Traceback (most recent call last):
  File "/data/data/com.termux/files/home/btc-hack/btc-hack.py", line 120, in <module>
    pool.close()
NameError: name 'pool' is not defined. Did you mean: 'bool'?""
