### ISSUE TITLE
Program is stuck at launch

### ISSUE THREAD

**Issue by 21Infinity** [DavidMGilbert/btc-hack#3]
Hello David,

First i want to thank you for your script.

I tried to launch it but nothing appears on the screen.
No error bu not adresses printed.
I use Python 3.9 and all the needed packages have been installed.

Do you have an idea where it could come from ?
The API is still useable?

Have a good day

**Comment by DavidMGilbert** [comment]
I would have a look at your python version and make sure you have the following modules installed.

requests
ecdsa
base58

Code is still running fine on my ubuntu 20.x box as I write this.

**Comment by 21Infinity** [comment]
Thanks for your answer.

I ran it on Python 3.9.1 and 3.8.7 (Windows).

At first launch the package has been installed without problem.
Then after launch, program hangs.

Do you think it could come from those versions ?

**Comment by DavidMGilbert** [comment]
No sure, As I said, code is still running fine, it could be a number of different things that are causing the problem.. I'd suggest you try un-installing and re-installing python.

**Comment by 21Infinity** [comment]
I installed ubuntu on Windows and reinstalled Python 3.8.

Now it runs fine.

You're a Boss :)

**Comment by DavidMGilbert** [comment]
Awesome work! I'll close this issue off.
