### ISSUE TITLE
ModuleNotFoundError: No module named 'base58' ( UBUNTU 20.04)

### ISSUE THREAD

**Issue by gtmylab** [DavidMGilbert/btc-hack#8]
root@ubuntu-4gb-hel1-1:~/btc-hack# python3 btc-hack.py
/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "btc-hack.py", line 16, in <module>
    import base58
ModuleNotFoundError: No module named 'base58'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "btc-hack.py", line 24, in <module>
    subprocess.check_call(["python3", '-m', 'pip', 'install', 'base58==1.0.0'])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', 'base58==1.0.0']' returned non-zero exit status 1.

**Comment by DavidMGilbert** [comment]
Try re-installing python.
